version: '3'

services:

  broker-service:
    image: homayoonalimohammadi/broker-service:1.0
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1
    container_name: BrokerApp

  authentication-service:
    image: homayoonalimohammadi/authentication-service:1.0
    restart: always
    ports:
      - "8081:80"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5"
    depends_on:
      - postgres
    container_name: AuthApp

    
  postgres:
    image: "postgres:12.12"
    restart: always
    ports:
      - "5432:5432"
    environmenet:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
    deploy: 
      mode: global 
    container_name: PostgresDB

  mongo:
    image: "mongo:4.2.16-bionic"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: logs 
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    deploy:
      mode: global 
    volumes:
     - ./db-data/mongo/:/data/db
    container_name: MongoDB

  logger-service:
    image: homayoonalimohammadi/logger-service:1.0
    restart: always
    environment:
      MONGO_INITDB_DATABASE: "logs" 
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "password"
    deploy:
      mode: replicated 
      replicas: 1
    container_name: LoggerApp

  mailhog:
    image: "mailhog/mailhog:v1.0.1"
    ports:
      - "8025:8025"
    deploy:
      mode: global 
    container_name: MailHog

  mail-service:
    image: homayooalimohammadi/mail-service:1.0
    restart: always 
    environment:
      MAIL_DOMAIN: localhost
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      MAIL_ENCRYPTION: none
      MAIL_FROM_NAME: "Homayoon Alimohammadi"
      MAIL_FROM_ADDRESS: "homayoon.alimohammadi@divar.ir"
    deploy:
      mode: replicated 
      replicas: 1
    container_name: MailApp
    
  rabbitmq:
    image: "rabbitmq:3.10-alpine"
    ports: 
      - "5672:5672"
    restart: always
    deploy: 
      mode: global
    container_name: RabbitMQ

  listener-service:
    image: homayoonalimohammadi/listener-service:1.0
    deploy:
      mode: replicated 
      replicas: 1
    container_name: ListernerApp